apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"pod":"sit2"},"name":"goose-metrixdb","namespace":"hubs"},"spec":{"containers":[{"command":["metrix-goose","-config","/etc/hubs/backend.toml","status"],"image":"example/image:v19.8.8-2","imagePullPolicy":"IfNotPresent","name":"goose-metrixdb","volumeMounts":[{"mountPath":"/etc/hubs/","name":"backend-config-volume"}]}],"imagePullSecrets":[{"name":"docker-hub-pressly"}],"restartPolicy":"Never","volumes":[{"configMap":{"items":[{"key":"backend.toml","path":"backend.toml"}],"name":"backend-config"},"name":"backend-config-volume"}]}}
    kubernetes.io/psp: eks.privileged
    linkerd.io/created-by: linkerd/proxy-injector stable-2.4.0
    linkerd.io/identity-mode: default
    linkerd.io/inject: enabled
    linkerd.io/proxy-version: stable-2.4.0
  creationTimestamp: "2019-08-18T12:23:27Z"
  labels:
    linkerd.io/control-plane-ns: linkerd
    pod: sit2
  name: goose-metrixdb
  namespace: hubs
  resourceVersion: "6261020"
  selfLink: /api/v1/namespaces/hubs/pods/goose-metrixdb
  uid: fb12b76f-c1b2-11e9-81c4-0a6b0408a2d6
spec:
  containers:
  - command:
    - metrix-goose
    - -config
    - /etc/hubs/backend.toml
    - status
    image: example/image:v19.8.8-2
    imagePullPolicy: IfNotPresent
    name: goose-metrixdb
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/hubs/
      name: backend-config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rbjzw
      readOnly: true
  - env:
    - name: LINKERD2_PROXY_LOG
      value: warn,linkerd2_proxy=info
    - name: LINKERD2_PROXY_DESTINATION_SVC_ADDR
      value: linkerd-destination.linkerd.svc.cluster.local:8086
    - name: LINKERD2_PROXY_CONTROL_LISTEN_ADDR
      value: 0.0.0.0:4190
    - name: LINKERD2_PROXY_ADMIN_LISTEN_ADDR
      value: 0.0.0.0:4191
    - name: LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR
      value: 127.0.0.1:4140
    - name: LINKERD2_PROXY_INBOUND_LISTEN_ADDR
      value: 0.0.0.0:4143
    - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
      value: svc.cluster.local.
    - name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
      value: 10000ms
    - name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
      value: 10000ms
    - name: _pod_ns
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: LINKERD2_PROXY_DESTINATION_CONTEXT
      value: ns:$(_pod_ns)
    - name: LINKERD2_PROXY_IDENTITY_DIR
      value: /var/run/linkerd/identity/end-entity
    - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
      value: |
        -----BEGIN CERTIFICATE-----
        MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
        eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwODAxMTQ1MjM1WhcNMjAwNzMx
        MTQ1MjU1WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
        YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARXALyhjZsShb439gRTG5r88BSE
        RJG6PvamMrqBZXst6ekclb9ilNHpbRpxJzu1LrKqXGMTo20b9ky/KgPodoLeo0Iw
        QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
        MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhANYgCbtFqLLIgdjY
        fTDbDyPrkD5JUYTdSCITInA3goVeAiBcBtIMRataJ2L/3ON3YjNuQH1qW2uUqv2m
        +1m6LU+/5g==
        -----END CERTIFICATE-----
    - name: LINKERD2_PROXY_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: LINKERD2_PROXY_IDENTITY_SVC_ADDR
      value: linkerd-identity.linkerd.svc.cluster.local:8080
    - name: _pod_sa
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: _l5d_ns
      value: linkerd
    - name: _l5d_trustdomain
      value: cluster.local
    - name: LINKERD2_PROXY_IDENTITY_LOCAL_NAME
      value: $(_pod_sa).$(_pod_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
    - name: LINKERD2_PROXY_IDENTITY_SVC_NAME
      value: linkerd-identity.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
    - name: LINKERD2_PROXY_DESTINATION_SVC_NAME
      value: linkerd-controller.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
    image: gcr.io/linkerd-io/proxy:stable-2.4.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: 4191
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: linkerd-proxy
    ports:
    - containerPort: 4143
      name: linkerd-proxy
      protocol: TCP
    - containerPort: 4191
      name: linkerd-admin
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 4191
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 2102
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rbjzw
      readOnly: true
    - mountPath: /var/run/linkerd/identity/end-entity
      name: linkerd-identity-end-entity
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: docker-hub-pressly
  initContainers:
  - args:
    - --incoming-proxy-port
    - "4143"
    - --outgoing-proxy-port
    - "4140"
    - --proxy-uid
    - "2102"
    - --inbound-ports-to-ignore
    - 4190,4191
    - --outbound-ports-to-ignore
    - "4222"
    image: gcr.io/linkerd-io/proxy-init:v1.0.0
    imagePullPolicy: IfNotPresent
    name: linkerd-init
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 10Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rbjzw
      readOnly: true
  nodeName: ip-10-170-24-11.us-west-2.compute.internal
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: backend.toml
        path: backend.toml
      name: backend-config
    name: backend-config-volume
  - name: default-token-rbjzw
    secret:
      defaultMode: 420
      secretName: default-token-rbjzw
  - emptyDir:
      medium: Memory
    name: linkerd-identity-end-entity
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-08-18T12:23:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-08-18T12:23:27Z"
    message: 'containers with unready status: [goose-metrixdb]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-08-18T12:23:27Z"
    message: 'containers with unready status: [goose-metrixdb]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-08-18T12:23:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4c8f41a68f347a01c316ff28684d6216faaa92d5b75d8762cde029e2852f436b
    image: example/image:v19.8.8-2
    imageID: docker-pullable://example/image@sha256:628f3e8dd81d5435a1db1eef01bb6b29c4ee9b0634f06018a37f35b78962cd9c
    lastState: {}
    name: goose-metrixdb
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://4c8f41a68f347a01c316ff28684d6216faaa92d5b75d8762cde029e2852f436b
        exitCode: 0
        finishedAt: "2019-08-18T12:23:29Z"
        reason: Completed
        startedAt: "2019-08-18T12:23:29Z"
  - containerID: docker://57568a2e5d987955ea3887bf04df5fe7a3ce64f6f12c7545230a36d63333998b
    image: gcr.io/linkerd-io/proxy:stable-2.4.0
    imageID: docker-pullable://gcr.io/linkerd-io/proxy@sha256:1c356e3784be1a62220cf92cb0438aa35c8ba152d8c06ddf63c2c3f6c1875b3b
    lastState: {}
    name: linkerd-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-08-18T12:23:30Z"
  hostIP: 10.170.24.11
  initContainerStatuses:
  - containerID: docker://577c6dbe88f2af47fc66be6927d64091027d3622520216a50e2daefd998026c4
    image: gcr.io/linkerd-io/proxy-init:v1.0.0
    imageID: docker-pullable://gcr.io/linkerd-io/proxy-init@sha256:b88af208664c1c82a55867e03f41d22f564cddf873e1524c7a854296371a6eff
    lastState: {}
    name: linkerd-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://577c6dbe88f2af47fc66be6927d64091027d3622520216a50e2daefd998026c4
        exitCode: 0
        finishedAt: "2019-08-18T12:23:28Z"
        reason: Completed
        startedAt: "2019-08-18T12:23:28Z"
  phase: Running
  podIP: 10.170.24.93
  qosClass: Burstable
  startTime: "2019-08-18T12:23:27Z"